pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
urlpatterns = [
    path('', views.index, name='index'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
    path('order/', views.order, name='order'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

pizzas/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

pizzas/forms.py
from django import forms
from .models import Topping

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name': ''}

class OrderForm(forms.Form):
    toppings = forms.ModelMultipleChoiceField(
        queryset=Topping.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Select your toppings:"
    )

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza
from .forms import ToppingForm, OrderForm

def index(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/index.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)
        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'pizza': pizza, 'toppings': toppings, 'form': form}
    return render(request, 'pizzas/pizza.html', context)

def order(request):
    if request.method != 'POST':
        form = OrderForm()
    else:
        form = OrderForm(data=request.POST)
        if form.is_valid():
            selected_toppings = form.cleaned_data['toppings']
            
            total_price = 10.00
            
            for topping in selected_toppings:
                total_price += topping.price

            context = {
                'form': form,
                'selected_toppings': selected_toppings,
                'total_price': total_price,
            }
            
            return render(request, 'pizzas/order.html', context)
    
    context = {'form': form}
    return render(request, 'pizzas/order.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width", initial-scale="1.0">
        <title>Pizzeria</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'pizzas:index' %}">Pizzeria</a>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div>
    </body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block header %}
    <h2>Pizzas</h2>
{% endblock header %}

{% block content %}
    <ul>
        {% for pizza in pizzas %}
        <li>
            <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
        </li>
        {% empty %}
        <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>
    {% endblock content %}

pizzas/templates/pizzas/order.html
{% extends "pizzas/base.html" %}

{% block header %}
  <h2>Place your order</h2>
{% endblock header %}

{% block content %}

  {% if selected_toppings %}
    <p>Your order has been placed! Here is the summary:</p>
    <ul>
    {% for topping in selected_toppings %}
        <li>{{ topping.name }}</li>
    {% endfor %}
    </ul>
    <p><strong>Total Price: ${{ total_price|floatformat:2 }}</strong></p>
    <hr>
    <p>Place another order:</p>
  {% endif %}

  <form action="{% url 'pizzas:order' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Place Order</button>
  </form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block header %}
  <h2>{{ pizza.name }}</h2>
{% endblock header %}

{% block content %}
  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>{{ topping.name }}</li>
    {% empty %}
      <li>This pizza has no toppings listed yet.</li>
    {% endfor %}
  </ul>
  
  <hr>
  <p>Add a new topping:</p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topping</button>
  </form>
  
{% endblock content %}